# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='python-service.proto',
  package='br.edu.ifpb.lib',
  syntax='proto3',
  serialized_options=_b('\n\017br.edu.ifpb.libP\001'),
  serialized_pb=_b('\n\x14python-service.proto\x12\x0f\x62r.edu.ifpb.lib\x1a\x1bgoogle/protobuf/empty.proto\",\n\x08\x44ocument\x12\x12\n\nidDocument\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\x0c\"Z\n\x1c\x46requencyDistributionRequest\x12+\n\x08\x64ocument\x18\x01 \x01(\x0b\x32\x19.br.edu.ifpb.lib.Document\x12\r\n\x05total\x18\x02 \x01(\x05\"+\n\tFrequency\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\":\n\x11\x44ocumentoConteudo\x12\x13\n\x0bidDocumento\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\t\"\\\n\x15\x46requencyDistribution\x12\x12\n\nidDocument\x18\x01 \x01(\t\x12/\n\x0b\x66requencies\x18\x02 \x03(\x0b\x32\x1a.br.edu.ifpb.lib.Frequency\")\n\x13RecomendacaoRequest\x12\x12\n\nidDocument\x18\x01 \x01(\t\"A\n\x15RecomendacaoDocumento\x12\x12\n\nidDocument\x18\x01 \x01(\t\x12\x14\n\x0csimilaridade\x18\x02 \x01(\x01\"U\n\x14RecomendacaoResponse\x12=\n\rrecomendacoes\x18\x01 \x03(\x0b\x32&.br.edu.ifpb.lib.RecomendacaoDocumento2\x85\x01\n\x0f\x44ocumentService\x12r\n\x19\x66indFrequencyDistribution\x12-.br.edu.ifpb.lib.FrequencyDistributionRequest\x1a&.br.edu.ifpb.lib.FrequencyDistribution2\xb4\x01\n\x03Lda\x12]\n\x1dtreinarModeloLDAComDocumentos\x12\".br.edu.ifpb.lib.DocumentoConteudo\x1a\x16.google.protobuf.Empty(\x01\x12N\n\x10treinarModeloLDA\x12\".br.edu.ifpb.lib.DocumentoConteudo\x1a\x16.google.protobuf.Empty2\xd1\x01\n\x0cRecomendacao\x12\x62\n\x13\x62uscarRecomendacoes\x12$.br.edu.ifpb.lib.RecomendacaoRequest\x1a%.br.edu.ifpb.lib.RecomendacaoResponse\x12]\n\x1dremoverDocumentoDoTreinamento\x12$.br.edu.ifpb.lib.RecomendacaoRequest\x1a\x16.google.protobuf.EmptyB\x13\n\x0f\x62r.edu.ifpb.libP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='br.edu.ifpb.lib.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idDocument', full_name='br.edu.ifpb.lib.Document.idDocument', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='br.edu.ifpb.lib.Document.file', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=114,
)


_FREQUENCYDISTRIBUTIONREQUEST = _descriptor.Descriptor(
  name='FrequencyDistributionRequest',
  full_name='br.edu.ifpb.lib.FrequencyDistributionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='document', full_name='br.edu.ifpb.lib.FrequencyDistributionRequest.document', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='br.edu.ifpb.lib.FrequencyDistributionRequest.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=206,
)


_FREQUENCY = _descriptor.Descriptor(
  name='Frequency',
  full_name='br.edu.ifpb.lib.Frequency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='br.edu.ifpb.lib.Frequency.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='br.edu.ifpb.lib.Frequency.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=251,
)


_DOCUMENTOCONTEUDO = _descriptor.Descriptor(
  name='DocumentoConteudo',
  full_name='br.edu.ifpb.lib.DocumentoConteudo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idDocumento', full_name='br.edu.ifpb.lib.DocumentoConteudo.idDocumento', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conteudo', full_name='br.edu.ifpb.lib.DocumentoConteudo.conteudo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=311,
)


_FREQUENCYDISTRIBUTION = _descriptor.Descriptor(
  name='FrequencyDistribution',
  full_name='br.edu.ifpb.lib.FrequencyDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idDocument', full_name='br.edu.ifpb.lib.FrequencyDistribution.idDocument', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequencies', full_name='br.edu.ifpb.lib.FrequencyDistribution.frequencies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=405,
)


_RECOMENDACAOREQUEST = _descriptor.Descriptor(
  name='RecomendacaoRequest',
  full_name='br.edu.ifpb.lib.RecomendacaoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idDocument', full_name='br.edu.ifpb.lib.RecomendacaoRequest.idDocument', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=448,
)


_RECOMENDACAODOCUMENTO = _descriptor.Descriptor(
  name='RecomendacaoDocumento',
  full_name='br.edu.ifpb.lib.RecomendacaoDocumento',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idDocument', full_name='br.edu.ifpb.lib.RecomendacaoDocumento.idDocument', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similaridade', full_name='br.edu.ifpb.lib.RecomendacaoDocumento.similaridade', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=515,
)


_RECOMENDACAORESPONSE = _descriptor.Descriptor(
  name='RecomendacaoResponse',
  full_name='br.edu.ifpb.lib.RecomendacaoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recomendacoes', full_name='br.edu.ifpb.lib.RecomendacaoResponse.recomendacoes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=602,
)

_FREQUENCYDISTRIBUTIONREQUEST.fields_by_name['document'].message_type = _DOCUMENT
_FREQUENCYDISTRIBUTION.fields_by_name['frequencies'].message_type = _FREQUENCY
_RECOMENDACAORESPONSE.fields_by_name['recomendacoes'].message_type = _RECOMENDACAODOCUMENTO
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['FrequencyDistributionRequest'] = _FREQUENCYDISTRIBUTIONREQUEST
DESCRIPTOR.message_types_by_name['Frequency'] = _FREQUENCY
DESCRIPTOR.message_types_by_name['DocumentoConteudo'] = _DOCUMENTOCONTEUDO
DESCRIPTOR.message_types_by_name['FrequencyDistribution'] = _FREQUENCYDISTRIBUTION
DESCRIPTOR.message_types_by_name['RecomendacaoRequest'] = _RECOMENDACAOREQUEST
DESCRIPTOR.message_types_by_name['RecomendacaoDocumento'] = _RECOMENDACAODOCUMENTO
DESCRIPTOR.message_types_by_name['RecomendacaoResponse'] = _RECOMENDACAORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.Document)
  })
_sym_db.RegisterMessage(Document)

FrequencyDistributionRequest = _reflection.GeneratedProtocolMessageType('FrequencyDistributionRequest', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYDISTRIBUTIONREQUEST,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.FrequencyDistributionRequest)
  })
_sym_db.RegisterMessage(FrequencyDistributionRequest)

Frequency = _reflection.GeneratedProtocolMessageType('Frequency', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCY,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.Frequency)
  })
_sym_db.RegisterMessage(Frequency)

DocumentoConteudo = _reflection.GeneratedProtocolMessageType('DocumentoConteudo', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTOCONTEUDO,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.DocumentoConteudo)
  })
_sym_db.RegisterMessage(DocumentoConteudo)

FrequencyDistribution = _reflection.GeneratedProtocolMessageType('FrequencyDistribution', (_message.Message,), {
  'DESCRIPTOR' : _FREQUENCYDISTRIBUTION,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.FrequencyDistribution)
  })
_sym_db.RegisterMessage(FrequencyDistribution)

RecomendacaoRequest = _reflection.GeneratedProtocolMessageType('RecomendacaoRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMENDACAOREQUEST,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.RecomendacaoRequest)
  })
_sym_db.RegisterMessage(RecomendacaoRequest)

RecomendacaoDocumento = _reflection.GeneratedProtocolMessageType('RecomendacaoDocumento', (_message.Message,), {
  'DESCRIPTOR' : _RECOMENDACAODOCUMENTO,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.RecomendacaoDocumento)
  })
_sym_db.RegisterMessage(RecomendacaoDocumento)

RecomendacaoResponse = _reflection.GeneratedProtocolMessageType('RecomendacaoResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMENDACAORESPONSE,
  '__module__' : 'python_service_pb2'
  # @@protoc_insertion_point(class_scope:br.edu.ifpb.lib.RecomendacaoResponse)
  })
_sym_db.RegisterMessage(RecomendacaoResponse)


DESCRIPTOR._options = None

_DOCUMENTSERVICE = _descriptor.ServiceDescriptor(
  name='DocumentService',
  full_name='br.edu.ifpb.lib.DocumentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=605,
  serialized_end=738,
  methods=[
  _descriptor.MethodDescriptor(
    name='findFrequencyDistribution',
    full_name='br.edu.ifpb.lib.DocumentService.findFrequencyDistribution',
    index=0,
    containing_service=None,
    input_type=_FREQUENCYDISTRIBUTIONREQUEST,
    output_type=_FREQUENCYDISTRIBUTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DOCUMENTSERVICE)

DESCRIPTOR.services_by_name['DocumentService'] = _DOCUMENTSERVICE


_LDA = _descriptor.ServiceDescriptor(
  name='Lda',
  full_name='br.edu.ifpb.lib.Lda',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=741,
  serialized_end=921,
  methods=[
  _descriptor.MethodDescriptor(
    name='treinarModeloLDAComDocumentos',
    full_name='br.edu.ifpb.lib.Lda.treinarModeloLDAComDocumentos',
    index=0,
    containing_service=None,
    input_type=_DOCUMENTOCONTEUDO,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='treinarModeloLDA',
    full_name='br.edu.ifpb.lib.Lda.treinarModeloLDA',
    index=1,
    containing_service=None,
    input_type=_DOCUMENTOCONTEUDO,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LDA)

DESCRIPTOR.services_by_name['Lda'] = _LDA


_RECOMENDACAO = _descriptor.ServiceDescriptor(
  name='Recomendacao',
  full_name='br.edu.ifpb.lib.Recomendacao',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=924,
  serialized_end=1133,
  methods=[
  _descriptor.MethodDescriptor(
    name='buscarRecomendacoes',
    full_name='br.edu.ifpb.lib.Recomendacao.buscarRecomendacoes',
    index=0,
    containing_service=None,
    input_type=_RECOMENDACAOREQUEST,
    output_type=_RECOMENDACAORESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removerDocumentoDoTreinamento',
    full_name='br.edu.ifpb.lib.Recomendacao.removerDocumentoDoTreinamento',
    index=1,
    containing_service=None,
    input_type=_RECOMENDACAOREQUEST,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOMENDACAO)

DESCRIPTOR.services_by_name['Recomendacao'] = _RECOMENDACAO

# @@protoc_insertion_point(module_scope)
